version: '3'

services:
  web:
    build: test_vk_api/.
    env_file:
      - env_private/web.env
    environment:
      - DJANGO_DEBUG=false
    volumes:
      - ./test_vk_api:/usr/src/test_vk_api

#  celery:
#    build: ./test_vk_api/.
#    env_file:
#      - env_private/web.env
#    volumes:
#      - ./test_vk_api:/usr/src/test_vk_api
#    depends_on:
#      - redis
#      - web
#    command:
#      - celery -A test_vk_api -l info

  redis:
    image: redis:alpine
